# Clip Page
# This script creates a clip page
# Designed for AYTClips.

# I'll fix this up later.
# I just want to see if this
# may be a better idea to where
# when you click on a clip link,
# it opens a new tab with a UI of
# such clip. But, I'm also not too
# sure what I am doing with this lol,
# I guess something will come to my mind.

cat > headsupbirthdaysecurityquestions.html
cat > youcanhaveyourcakeandeatittoo.html
cat > end2endencryption.html
cat > depression.html
cat > buffer.html
cat > qemukvm.html
cat > entropydataset.html
cat > dowhatyouenjoyinyourlife.html
cat > oldformofpemdas.html
cat > backup.html
cat > graphicsapi.html
cat > compilekernel.html
cat > hackintosh.html
cat > iosdevelopment.html
cat > bittorrent.html
cat > tracker.html
cat > datayoureproducecandictatethelifegoingforward.html
cat > inordertofunctiontheworldwecreated.html
cat > downloadingfromyourservice.html
cat > privacyisabasichumanright.html
cat > idontcarebutdocare.html
cat > ipaddress.html
cat > cache.html
cat > macros.html
cat > adminprivileges.html
cat > badportforwarding.html
cat > 18.html
cat > executingfiles.html
cat > encryptionkeys.html
cat > wo.html
cat > relationships.html
cat > firewall.html
cat > billc11billc10.html
cat > masturbation.html
cat > donthelp.html
cat > appbased2fa.html
cat > sudoplusroot.html
cat > woof.html
cat > cpu.html
cat > protectyourdata.html
cat > softwareemulation.html
cat > callitanight.html
cat > linda.html
cat > supplychainattack.html
cat > androidrgbcolourspace.html
cat > 5muslimprayers.html
cat > sellingsoftwareandopensource.html
cat > rosettatranslatesx86toarm.html
cat > youtubecsai.html
cat > preventphisingemailscams.html
cat > ilysmidkhtf.html
cat > whyusanantiviruswhenthereiswindowsdefender.html
cat > howtosetupavpnongtaonline.html
cat > eh.html
cat > netflixareyoustillwatchingsomeonesdaughter.html
cat > dmcaexception.html
cat > 30virtualmachinespreformance.html
cat > hahaha.html
cat > freedominternet.html
cat > moralargument.html
cat > ithinkthatsbad.html
cat > tics.html
cat > firepit.html
cat > havingmultiplechoices.html
cat > humantrafficking.html
cat > ttyl.html
cat > cpuemulation.html
cat > nevershootinorder.html
cat > perspective.html
cat > aiandmachinelearning.html
cat > privatecomputecore.html
cat > videogamealive.html
cat > ddos.html
cat > macaddress.html
cat > schoolstudentnames.html
cat > pciexpressslot.html
cat > compatibiltylayer.html
cat > copyrightandtrademark.html
cat > edwardsnowden
cat > packetloss.html
cat > patience.html
cat > ifyoufollowyourpassionitllleadtosuccess.html
cat > ispiracymorallyok.html
cat > fivefeaturesofdatawarehousing.html
cat > jsonmetadata.html
cat > cyberattack.html
cat > neverdownloadanythingfromotherswithoutsendingitthroughsomethinglikevirustotal.html
cat > privacyisgettingrazarthin.html
cat > md5checksum.html
cat > dataismoreworthhangold.html
cat > mostcomputerscanrunavmextrasecurity.html
cat > sexeducation.html
cat > maskbankingdetails.html
cat > literally.html
cat > suckstobealinuxuser.html
cat > dazwatcheshorror.html
cat > ingamedoxxer.html
cat > job.html
cat > trustlevelcolourcoded.html
cat > weewoo.html
cat > mostdo.html
cat > favouritememoriessantaclause.html
cat > twitchterrified.html
cat > macros.html
cat > muta.html
cat > beagoodpersion.html
cat > surveysaresketchy.html
cat > youserious.html
cat > lemon.html
cat > mentaloutlawprivacy.html
cat > suckitoffandthrowitaway.html
cat > linuxmonolithickernel.html
cat > mousesoftware.html
cat > usingproprietarysoftware.html
cat > lolwhathefun.html
cat > 100precent.html
cat > linuxchromeosgaming.html
cat > webbrowser.html
cat > schoolproblem.html
cat > uranus.html
cat > facebook.html
cat > enderman.html
cat > odysee.html
cat > momsbithenaboutlifedazblack.html
cat > beingacontentcreatorisexhausting.html
cat > monsterscrashadams.html
cat > badexampleofelseifstatements.html
cat > nebulamaingoal.html
cat > simswapstopusingsms2mfa.html
cat > me.html
cat > g1andg2driverlicense.html
cat > tearswithjoyemoji.html
cat > helpyouunderstandlinux.html
cat > decrepitos.html
cat > emojithataytclipscantunderstand.html
cat > noodle.html
cat > curiousgeorge.html
cat > dotdotdot.html
cat > cucumber.html